### ISSUE TITLE
How to create large pdf file?

### ISSUE THREAD

**Issue by amandeepmittal** [vnglst/form-to-pdf#1]
I read your tutorial and tried your demo. Thanks for both. Out of curiosity, just wanted to know how to add multiple pages while creating the text or to set the length of a page in the document?

**Comment by vnglst** [comment]
You can do most of those things with the module PDFKit I've used in the tutorial (see pdf.js). They've got a great website with an interactive demo! Creating pages etc. is pretty easy with that. See: http://pdfkit.org/

**Comment by amandeepmittal** [comment]
@vnglst will check it out.
